import { Inter } from 'next/font/google';

import './globals.css';
import type { Metadata } from 'next';

import SWRConfigContext from '@/src/app/SWRConfigContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
SWRConfigContext;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SWRConfigContext>{children}</SWRConfigContext>
      </body>
    </html>
  );
}
